### ISSUE TITLE
Support interchangeable middleware on a per-request basis

### ISSUE THREAD

**Issue by rdlowrey** [rdlowrey/aerys#34]
`Host` instances should be configurable with generic middleware to transform requests and responses. The middleware API should allow modifying incoming/outgoing headers but also streaming entity body data in both directions.

**Proposed Middleware Hooks**

- `before`

Invoked after all request headers are received (but before any entity body data processing) to allow request transformations.

- `during`

Invoked after the initial response is assigned but before any output is dispatched to the client.

- `after`

Invoked after response write completion (e.g. to allow request logging).

**Comment by bwoebi** [comment]
This issue is obsolete with the current Middleware Generator approach.
